---
name: Workflow Lint

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint GitHub Actions workflows
        uses: github/super-linter@v4
        env:
          VALIDATE_WORKFLOWS: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: false
          VALIDATE_TERRAFORM: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
